### ISSUE TITLE
How to import txt data from txt file

### ISSUE THREAD

**Issue by wilcar** [juba/rainette#1]
Hi, thank you for your great job. I am dealing with .txt files (with **** on top and bottom for Iramuteq)

![image](https://user-images.githubusercontent.com/18226229/70604673-5419b900-1bf9-11ea-9e74-71ca84d385fa.png)

       # example of readling text files : 
         fichier <- readLines("testfinal.tx")

According to your vignette : 

         corpus <- import_corpus_iramuteq(fichier)

return me this error :

       Error in file(f, ...) : invalid 'description' argument

Can you help me ?

**Comment by juba** [comment]
Hi,

The first argument to `import_corpus_iramuteq` should be a connection or filename, not the result of `readLines`. So maybe the following would work : 

```r
corpus <- import_corpus_iramuteq("testfinal.txt")
```

Let me know if it doesn't...

**Comment by juba** [comment]
Je passe en français du coup :-)

Vu l'aperçu de votre fichier texte, je ne suis pas sûr que l'importer tel quel donnera de bons résultats. Vous avez du "vrai texte" à un moment donné ou ce ne sont que des champs avec des valeurs comme "Langue", "Format", "Identifiant", etc. ?

**Comment by wilcar** [comment]
Bonjour, c'est un vrai texte et cela fonctionne.
Merci pour votre aide.
