### ISSUE TITLE
Problème de lecture de corpus de texte - rainette

### ISSUE THREAD

**Issue by CreaPolitics** [juba/rainette#10]
Bonjour,
Merci énormément pour ce package, qui promet d'être très intéressant à l'utilisation.
N'étant pas un professionnel de "R", je me trompe peut être dans la façon d'effectuer mes analyses, et je m'excuse d'avance si ma question peut sembler idiote.

J'essaie de m'entrainer à utiliser votre package, et j'arrive à installer l'ensemble (il me semble tout à fait correctement).
Au moment de lancer le package, pas de problèmes pour répéter les opérations que vous avez mis en avant, mais arrivé à la lecture du corpus, ou les apostrophes, accents et cédilles prennent des formes étranges (voir capture d'écran). 

<img width="498" alt="Capture3" src="https://user-images.githubusercontent.com/84035894/117857336-f0cc0480-b28c-11eb-9ff6-bdac860a7215.PNG">

J'ai passé le Spelling en Français

<img width="551" alt="Capture" src="https://user-images.githubusercontent.com/84035894/117856865-6c798180-b28c-11eb-95f8-141651524f6f.PNG">

Et le code d'ouverture des fichiers de sauvegardes en UTF8

<img width="590" alt="Capture2" src="https://user-images.githubusercontent.com/84035894/117856999-992d9900-b28c-11eb-8ecc-6646c41fd436.PNG">

Malheureusement, ce bug semble compromettre toutes les autres analyses.

<img width="755" alt="Capture4" src="https://user-images.githubusercontent.com/84035894/117857958-a8611680-b28d-11eb-9bac-34d5a8841852.PNG">

Je suppose que j'ai du oublier quelque chose d'assez basique... Vraiment désolé pour le dérangement en tout cas, et merci d'avance pour votre aide.

Bien cordialement,

**Comment by juba** [comment]
Ah, c'est l'éternel souci d'encodage quand on travaille sous Windows malheureusement. Est-ce que vous pouvez essayer de rajouter l'option `encoding` suivante à `import_corpus_iramuteq`, voir si ça résout le problème ?

```r
corpus <- import_corpus_iramuteq(fichier, encoding="UTF-8")
```

**Comment by CreaPolitics** [comment]
Absolument fantastique, tout marche !
