### ISSUE TITLE
Error: Package "FNN" needed when checking the box "Complete with k-nearest neighbours"

### ISSUE THREAD

**Issue by gabrielparriaux** [juba/rainette#20]
Hello,

When an analysis is being displayed with `rainette2_explor` and I check the box for "Complete with k-nearest neighbours", I get this error:

`Error: Package "FNN" needed for this function to work. Please install it.`

It was working fine before.

Do you have any idea of how I can solve this problem?

Thanks a lot,

Gabriel

**Comment by juba** [comment]
Yes, you can solve it by installing the `FNN` package :slightly_smiling_face:

**Comment by gabrielparriaux** [comment]
Perfect, thank you! Sorry for asking a question with such an evident answer…

**Comment by juba** [comment]
No problem at all !
