### ISSUE TITLE
Compatibility with R 4.3.0

### ISSUE THREAD

**Issue by gabrielparriaux** [juba/rainette#27]
Hi,

As R 4.3.0 has arrived recently, I was interested to update my system with this new version of R (and also the version of R Studio that goes with it), but I wonder if I will break something about **rainette**.

Is **rainette** compatible with this latest version of R?

More generally, how do we know, in case of an update of R, if we can update our system or not? 

Thanks a lot for your advice,

Gabriel

**Comment by juba** [comment]
`rainette` should be compatible with R 4.3 without issue. In general minor version updates (4.2 -> 4.3) should not cause major issues at least for packages that are actively maintained. But if you prefer you can always wait for a few weeks/months before upgrading as it will give package maintainers some time to fix problems.

**Comment by gabrielparriaux** [comment]
Thanks a lot for your advice! Good to know that `rainette` should be compatible with this new version of R yet!

I will probably wait some more weeks, anyway — as you advise too — because I’m working on some crucial analysis those days and I would not like to break my setup…
