### ISSUE TITLE
Dictionnaire et rainette_plot2()

### ISSUE THREAD

**Issue by manubonnet** [juba/rainette#3]
Bonjour,

Tout d'abord merci beaucoup pour ce package très complet et très efficace.

- Je ne suis pas certain d'être au bon endroit pour cela car la fonction dfm() ne provient pas du package rainette mais vous l'utilisez quand même... Ma première question était de savoir si je pouvais utiliser un dictionnaire au format IRaMuTeQ (aperçu ci-dessous)
![image](https://user-images.githubusercontent.com/44941577/73957178-4a18eb80-4906-11ea-83ec-6233014752a5.png)

-  Deuxième question, après un rainette2_plot(), existe-t-il une méthode simple pour récupérer les termes affichés sur le graphique obtenu en mode barplot?
Comme par exemple ces 2 colonnes que j'aimerais récupérer sous forme de matrice ou de liste
![image](https://user-images.githubusercontent.com/44941577/73956382-2903cb00-4905-11ea-84a0-7af37344710d.png)

Merci d'avance pour la réponse,

Cordialement

**Comment by juba** [comment]
Bonjour,

Pour le dictionnaire, c'est possible de la faire avec R/Quanteda en faisant de la substitution de termes. Je trouverais ça assez dommage cependant, si vous voulez faire de la lemmatisation il y a des packages a priori nettement plus puissants et intéressants comme `spacyr` ou `udpipe`.

Pour récupérer les données correspondant au graphique, c'est une très bonne question et il n'y a malheureusement pas de solution simple pour ça actuellement dans rainette. En gros le truc qui marcherait vagument serait quelque chose comme ça :

```
groups <- cutree_rainette(res, k = 3)
rainette:::keyness_stats(groups, dtm, "chi2", rlang::sym("chi2"), show_negative = TRUE, n_terms = 10)
```

Autant dire que ça n'est pas pratique. Il faut que je rajoute une fonction plus simple qui permettre de le faire.

**Comment by juba** [comment]
J'ai rajouté une issue (#4) pour ça du coup.

Merci d'avoir pris le temps de faire ce retour !

**Comment by manubonnet** [comment]
merci beaucoup pour la réponse rapide! et très efficace
