### ISSUE TITLE
Retrieve original (and most representative ?) segments of a lemmatized corpus after clustering

### ISSUE THREAD

**Issue by JacquesAntoine** [juba/rainette#30]
Hello,

Is there any way (with rainette) to retrieve the original segments of a lemmatized corpus after clustering.

I would like to illustrate the content of clusters with quotes from respondents (using e.g. the Cluster documents of rainette_explore).

That is with "natural" language" rather than with the sequence of lemmes.

Thank you very much,
Jacques-Antoine

**Comment by juba** [comment]
Hi,

If you apply your lemmatization (for example with `tokens_wordstem()`) after splitting your corpus into segments with `split_segments()`, you can easily retrieve cluster membership of your original segments with `cutree()`. The example in [the introduction](https://juba.github.io/rainette/articles/introduction_en.html) should get that I think (but maybe I didn't understand your request correctly ?).

**Comment by JacquesAntoine** [comment]
Hello,

Great, thank you very much (I confess I did the splitting after the lemmatization...) !

Best regards,
Jacques-Antoine
