### ISSUE TITLE
Translate words in rainette_plot() / textplot_network / textplot_cloud

### ISSUE THREAD

**Issue by JacquesAntoine** [juba/rainette#33]
Hello,

Is there a way to translate (in my case from French to English) the words that appear in the figures produced by rainette_plot() / textplot_network and textplot_cloud ?

Thank you very much,
Best regards,
Jacques-Antoine

**Comment by juba** [comment]
Hi, what are you trying to translate exactly, the text of the interface or the words in your corpus ?

**Comment by JacquesAntoine** [comment]
I try to translate the words of the corpus, more precisely the words that appear in the figures network, cloud and cluster (lexical worlds) (after analysis).

**Comment by JacquesAntoine** [comment]
It is for a publication

**Comment by juba** [comment]
I don't think there would be a way to translate the words without translating the corpus and rerun the analysis. By the way, `textplot_network()` and `textplot_wordcloud()` are not `rainette` functions, they are part of `quanteda`.

**Comment by JacquesAntoine** [comment]
OK, thank you very much for your time !
