### ISSUE TITLE
rainette2_plot() nombre et poucentage de non classés

### ISSUE THREAD

**Issue by manubonnet** [juba/rainette#5]
En regardant le code de rainette2_plot() il me semble que ces données sont implémentées pour s'afficher sur le graphique, mais je n'arrive pas à les avoir affichées... J'ai juste l'histogramme avec les NA mais pas très informatif en terme de réelle quantité de non classés

**Comment by juba** [comment]
Ah, oui, j'ai rajouté ça très récemment, normalement si vous réinstallez le package le nombre de NA devrait apparaître dans le titre du barplot.

N'hésitez pas à signaler si ça vous semble suffisant ou si d'autres informations seraient également utiles.

**Comment by manubonnet** [comment]
effectivement le package ne s'était pas bien mis à jour!
